apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/peikyaws/peiky-core-config-service:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/peikyaws/peiky-core-config-service:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: peiky-core-config-service
        chartPath: charts/peiky-core-config-service
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/peikyaws/peiky-core-config-service'
          image.tag: '{{.DIGEST_HEX}}'
